name: 'Test packages installation'
description: 'This action test packages installation in the windows runner where is executed'
inputs:
  tag:
    description: 'Tag of the integration to test'
    required: true
    default: 'v0.0.0'
  integration:
    description: 'Name of the integration to test'
    required: true
    default: 'test'
  arch:
    description: 'Architecture to test [amd64, 386]'
    required: true
    default: 'amd64'
  upgrade:
    description: 'Wether to test upgrade path as well'
    required: false
    default: "false"

runs:
  using: "composite"
  steps: 
    - run: |
        ${{ github.action_path }}\test_msi.ps1 ${{ inputs.integration }} ${{ inputs.arch }} ${{ inputs.tag }} ${{ inputs.upgrade }}
      shell: pwsh